# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/struct_oss1_pb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/struct_oss1_pb.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1aproto/struct_oss1_pb.proto\"A\n\x0c\x65ntity_attr2\x12\x0f\n\x07\x61ttr_id\x18\x01 \x02(\x05\x12\x11\n\tattribute\x18\x02 \x02(\x0c\x12\r\n\x05value\x18\x03 \x03(\x0c\"Y\n\x0c\x65ntity_desc2\x12\x11\n\tentity_id\x18\x01 \x02(\x05\x12\x13\n\x0b\x65ntity_name\x18\x02 \x02(\x0c\x12!\n\nattributes\x18\x03 \x03(\x0b\x32\r.entity_attr2')
)




_ENTITY_ATTR2 = _descriptor.Descriptor(
  name='entity_attr2',
  full_name='entity_attr2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attr_id', full_name='entity_attr2.attr_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='entity_attr2.attribute', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='entity_attr2.value', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=95,
)


_ENTITY_DESC2 = _descriptor.Descriptor(
  name='entity_desc2',
  full_name='entity_desc2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='entity_desc2.entity_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity_name', full_name='entity_desc2.entity_name', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='entity_desc2.attributes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=186,
)

_ENTITY_DESC2.fields_by_name['attributes'].message_type = _ENTITY_ATTR2
DESCRIPTOR.message_types_by_name['entity_attr2'] = _ENTITY_ATTR2
DESCRIPTOR.message_types_by_name['entity_desc2'] = _ENTITY_DESC2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

entity_attr2 = _reflection.GeneratedProtocolMessageType('entity_attr2', (_message.Message,), dict(
  DESCRIPTOR = _ENTITY_ATTR2,
  __module__ = 'proto.struct_oss1_pb_pb2'
  # @@protoc_insertion_point(class_scope:entity_attr2)
  ))
_sym_db.RegisterMessage(entity_attr2)

entity_desc2 = _reflection.GeneratedProtocolMessageType('entity_desc2', (_message.Message,), dict(
  DESCRIPTOR = _ENTITY_DESC2,
  __module__ = 'proto.struct_oss1_pb_pb2'
  # @@protoc_insertion_point(class_scope:entity_desc2)
  ))
_sym_db.RegisterMessage(entity_desc2)


# @@protoc_insertion_point(module_scope)
